spring:
  application:
    name: gestion-recrutement

  # MariaDB Configuration
  datasource:
    # url: jdbc:mariadb://localhost:3306/recrutement_db
    url: jdbc:mariadb://localhost:3306/recrutement_db?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: dev
    password: dev
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # File Upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidation12345M2
  expiration: 86400000

# File Storage
file:
  upload-dir: uploads

# Server Configuration
server:
  port: 8080
